postgresql:
  enabled: false  # Disable embedded PostgreSQL

externalDatabase:
  type: postgres
  # We'll use Kubernetes secrets for sensitive values
  host: "${POSTGRES_HOST}"  # Will be replaced with your Azure PostgreSQL server FQDN
  port: 5432
  database: "airflow"
  user: "${POSTGRES_USER}"  # Will be replaced with your PostgreSQL admin username
  # Use Kubernetes secret for password
  passwordSecret: "airflow-postgres-secret"
  passwordSecretKey: "postgres-password"
  # For Azure PostgreSQL Flexible Server
  properties: "?sslmode=require"

# Service account for Airflow to interact with Kubernetes API
serviceAccount:
  create: true
  name: "airflow-service-account"


workers:
  # Important: Must be false when logs.persistence.enabled=true
  logCleanup:
    enabled: false

# Ensure PgBouncer is properly configured
pgbouncer:
  enabled: true